"use client";
import { useEffect, useRef, useState } from "react";
import { Cancel01Icon, File01Icon, Search01Icon } from "@hugeicons/core-free-icons";
import { BackToTopButton } from "@/components/shared/BackToTopButton";
import { EmptyState } from "@/components/shared/EmptyState";
import { buildApplicationsApiHref } from "@/endpoints/student/application-query";
import type { ApplicationFilters, ApplicationListResponse, ApplicationRouteType } from "@/types/applications";
import { StudentApplicationCard } from "./StudentApplicationCard";
import { StudentApplicationCardSkeleton } from "./StudentApplicationCardSkeleton";
import styles from "./ApplicationFeed.module.css";

export function ApplicationFeed({ errorMessage, filters, initialData, onReset, type }: { errorMessage: string | null; filters: ApplicationFilters; initialData: ApplicationListResponse | null; onReset: () => void; type: ApplicationRouteType }) {
  const [items, setItems] = useState(initialData?.results ?? []); const [nextPage, setNextPage] = useState(initialData?.next ?? null); const [loadError, setLoadError] = useState(errorMessage); const [loading, setLoading] = useState(false); const loadingRef = useRef(false); const sentinelRef = useRef<HTMLDivElement>(null); const filtered = Boolean(filters.search || filters.status || filters.appliedFrom || filters.appliedTo);
  useEffect(() => { const target = sentinelRef.current; if (!target || !nextPage || loadError) return; const observer = new IntersectionObserver(([entry]) => { if (entry?.isIntersecting) void loadMore(); }, { rootMargin: "480px 0px" }); observer.observe(target); return () => observer.disconnect(); });
  async function loadMore() { if (!nextPage || loadingRef.current) return; loadingRef.current = true; setLoading(true); setLoadError(null); try { const response = await fetch(buildApplicationsApiHref(type, { ...filters, page: nextPage }), { headers: { Accept: "application/json" } }); const payload = await response.json() as ApplicationListResponse & { message?: string }; if (!response.ok || !Array.isArray(payload.results)) { setLoadError(payload.message ?? "More applications could not be loaded."); return; } setItems((current) => { const ids = new Set(current.map((item) => item.id)); return [...current, ...payload.results.filter((item) => !ids.has(item.id))]; }); setNextPage(payload.next); } catch { setLoadError("More applications could not be loaded. Check your connection and try again."); } finally { loadingRef.current = false; setLoading(false); } }
  if (!items.length) return <EmptyState actions={filtered ? [{ icon: Cancel01Icon, label: "Reset filters", onClick: onReset }] : [{ href: `/opportunities/${type}`, icon: File01Icon, label: "Browse opportunities" }]} icon={loadError ? Search01Icon : File01Icon} message={loadError ?? (filtered ? "No applications match the current search and filters." : `You have not submitted any ${type === "job-listings" ? "job" : "internship"} applications yet.`)} title={loadError ? "Unable to load applications" : filtered ? "No matching applications" : "No applications yet"} />;
  return <section className={styles.feed} aria-label="Application results"><div className={styles.grid} role="list">{items.map((application) => <div className={styles.gridItem} key={application.id} role="listitem"><StudentApplicationCard application={application} type={type} /></div>)}{loading ? Array.from({ length: 3 }, (_, index) => <div className={styles.gridItem} key={`loading-${index}`}><StudentApplicationCardSkeleton /></div>) : null}</div>{loadError ? <div className={styles.loadError} role="alert"><span>{loadError}</span><button onClick={() => void loadMore()} type="button">Try again</button></div> : null}<div aria-hidden="true" className={styles.sentinel} ref={sentinelRef} />{loading ? <p className={styles.loadingMessage} aria-live="polite" role="status">Loading more applications...</p> : null}{!nextPage && !loadError ? <p className={styles.endMessage}>All matching applications are shown.</p> : null}<BackToTopButton /></section>;
}
