"use client";
import { useState } from "react";
import Image from "next/image";
import { File01Icon, Video01Icon, ViewIcon } from "@hugeicons/core-free-icons";
import { HugeIcon } from "@/components/shared/HugeIcon";
import type { Resource } from "@/types/student-self-service";
import { ResourceAccessButton } from "./ResourceAccessButton";
import { formatFileSize, formatResourceDate, resourceInitials } from "./utils";
import styles from "./ResourceManagementRow.module.css";

export function ResourceManagementRow({ resource }: { resource: Resource }) {
  const [imageFailed, setImageFailed] = useState(false); const [ownerImageFailed, setOwnerImageFailed] = useState(false); const hasImage = Boolean(resource.image_url) && !imageFailed; const hasOwnerImage = Boolean(resource.owner?.image_url) && !ownerImageFailed; const visibility = resource.visibility === "GLOBAL" ? "Everyone signed in" : resource.visibility === "UNIVERSITY_ONLY" ? "Your university" : "Available to you";
  return <tr><td data-label="Resource"><div className={styles.identity}><span className={styles.cover} aria-hidden="true">{hasImage ? <Image alt="" fill onError={() => setImageFailed(true)} sizes="44px" src={resource.image_url as string} unoptimized /> : <HugeIcon icon={resource.type === "DOCUMENT" ? File01Icon : Video01Icon} size={19} />}</span><div className={styles.identityCopy}><strong>{resource.name}</strong><span>{resource.description || "A Talent Match career resource."}</span></div></div></td><td data-label="Content"><div className={styles.contentCell}><span className={styles.typeBadge} data-type={resource.type}>{resource.type === "DOCUMENT" ? "Document" : "Video"}</span><small>{resource.type === "DOCUMENT" ? `${resource.file_name ?? "Managed document"} · ${formatFileSize(resource.file_size_bytes)}` : "Secure external video"}</small></div></td><td data-label="Owner"><div className={styles.owner}><span className={styles.ownerAvatar} aria-hidden="true">{hasOwnerImage ? <Image alt="" fill onError={() => setOwnerImageFailed(true)} sizes="32px" src={resource.owner?.image_url as string} unoptimized /> : resourceInitials(resource.owner?.name ?? "Talent Match")}</span><span><strong>{resource.owner?.name ?? "Talent Match"}</strong><small>{resource.owner?.role?.toLowerCase() ?? "Platform resource"}</small></span></div></td><td data-label="Audience and date"><div className={styles.metaCell}><strong>{visibility}</strong><span>Published {formatResourceDate(resource.published_at)}</span></div></td><td data-label="Status"><label className={styles.statusControl} data-status="PUBLISHED"><span aria-hidden="true" /><select aria-label={`Publication state for ${resource.name}`} disabled value="PUBLISHED"><option value="PUBLISHED">Published</option></select></label></td><td data-label="Actions"><div className={styles.actions}>{resource.type === "VIDEO" && resource.video_url ? <a href={resource.video_url} rel="noreferrer" target="_blank"><HugeIcon icon={ViewIcon} size={14} />Watch</a> : <ResourceAccessButton resourceId={resource.id} />}</div></td></tr>;
}
