"use client";
import { useState, type FormEvent } from "react";
import { Calendar03Icon, Cancel01Icon, FilterHorizontalIcon, Search01Icon, SortByDown02Icon, Video01Icon, ViewIcon } from "@hugeicons/core-free-icons";
import { AdminFilterShell } from "@/components/shared/AdminFilterShell";
import { AuthButton } from "@/components/shared/AuthButton";
import { HugeIcon } from "@/components/shared/HugeIcon";
import { InputField } from "@/components/shared/InputField";
import { SelectField } from "@/components/shared/SelectField";
import { useLiveSearch } from "@/lib/use-live-search";
import type { ResourceFilters, ResourceOrdering, ResourceType, ResourceVisibility } from "@/types/resources";
import { RESOURCE_ORDERING_OPTIONS, RESOURCE_TYPE_OPTIONS, RESOURCE_VISIBILITY_OPTIONS } from "./constants";
import { buildResourcesHref } from "./utils";
import styles from "./ResourceManagementFilters.module.css";

export function ResourceManagementFilters({ filters, isPending, onNavigate }: { filters: ResourceFilters; isPending: boolean; onNavigate: (href: string) => void }) {
  const [search, setSearch] = useState(filters.search ?? ""); const [createdFrom, setCreatedFrom] = useState(filters.createdFrom ?? ""); const [createdTo, setCreatedTo] = useState(filters.createdTo ?? ""); const [type, setType] = useState(filters.type ?? ""); const [visibility, setVisibility] = useState(filters.visibility ?? ""); const [ordering, setOrdering] = useState<ResourceOrdering>(filters.ordering); const [dialogOpen, setDialogOpen] = useState(false); const active = Boolean(filters.search || filters.createdFrom || filters.createdTo || filters.type || filters.visibility || filters.ordering !== "-published_at");
  useLiveSearch({ appliedValue: filters.search, onSearch: (value) => onNavigate(buildResourcesHref({ ...filters, page: 1, search: value })), value: search });
  function applyFilters() { let from = date(createdFrom); let to = date(createdTo); if (from && to && from > to) [from, to] = [to, from]; setDialogOpen(false); const value = search.trim(); onNavigate(buildResourcesHref({ createdFrom: from, createdTo: to, ordering, page: 1, search: value.length >= 3 ? value : null, type: type ? type as ResourceType : null, visibility: visibility ? visibility as ResourceVisibility : null })); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); applyFilters(); }
  function reset() { setSearch(""); setCreatedFrom(""); setCreatedTo(""); setType(""); setVisibility(""); setOrdering("-published_at"); setDialogOpen(false); onNavigate("/resources"); }
  return <AdminFilterShell actionCount={3} actions={<><AuthButton className={styles.utilityButton} icon={FilterHorizontalIcon} onClick={() => setDialogOpen(true)} type="button" variant="secondary">Filter</AuthButton><AuthButton className={styles.utilityButton} icon={FilterHorizontalIcon} isLoading={isPending} type="submit">Apply</AuthButton><AuthButton className={styles.utilityButton} disabled={!active} icon={Cancel01Icon} onClick={reset} type="button" variant="secondary">Reset</AuthButton></>} ariaLabel="Resource filters" dateControls={<><div className={styles.dateField}><InputField icon={Calendar03Icon} label="From date" name="created_from" onChange={(event) => setCreatedFrom(event.target.value)} type="date" value={createdFrom} /></div><div className={styles.dateField}><InputField icon={Calendar03Icon} label="To date" name="created_to" onChange={(event) => setCreatedTo(event.target.value)} type="date" value={createdTo} /></div></>} dialog={dialogOpen ? <div className={styles.backdrop} role="presentation"><section aria-labelledby="resource-filter-title" aria-modal="true" className={styles.dialog} role="dialog"><header className={styles.dialogHeader}><div><span aria-hidden="true"><HugeIcon icon={FilterHorizontalIcon} size={20} /></span><div><h2 id="resource-filter-title">Refine resources</h2><p>Narrow your library by content and audience.</p></div></div><button onClick={() => setDialogOpen(false)} type="button">Close</button></header><div className={styles.dialogGrid}><SelectField icon={Video01Icon} label="Resource type" name="type" onChange={(event) => setType(event.target.value)} options={RESOURCE_TYPE_OPTIONS} value={type} /><SelectField icon={ViewIcon} label="Audience" name="visibility" onChange={(event) => setVisibility(event.target.value)} options={RESOURCE_VISIBILITY_OPTIONS} value={visibility} /><SelectField icon={SortByDown02Icon} label="Sort by" name="ordering" onChange={(event) => setOrdering(event.target.value as ResourceOrdering)} options={RESOURCE_ORDERING_OPTIONS} value={ordering} /></div><footer className={styles.dialogActions}><AuthButton icon={Cancel01Icon} onClick={reset} type="button" variant="secondary">Reset</AuthButton><AuthButton icon={FilterHorizontalIcon} onClick={applyFilters} type="button">Apply filters</AuthButton></footer></section></div> : null} onSubmit={submit}><div className={styles.searchField}><InputField icon={Search01Icon} label="Search resources" name="search" onChange={(event) => setSearch(event.target.value)} placeholder="Title or description, at least 3 characters" type="search" value={search} /></div></AdminFilterShell>;
}
function date(value: string) { return /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null; }
