import type { ResourceFilters, ResourceOrdering, ResourceType, ResourceVisibility } from "@/types/resources";
const TYPES = new Set(["DOCUMENT", "VIDEO"]); const VISIBILITIES = new Set(["GLOBAL", "UNIVERSITY_ONLY"]); const ORDERING = new Set(["created_at", "-created_at", "updated_at", "-updated_at", "name", "-name", "type", "-type", "published_at", "-published_at"]);
export function parseResourceFilters(query: Record<string, string | string[] | undefined>): ResourceFilters { const page = Number(read(query.page)); const search = read(query.search); const type = read(query.type)?.toUpperCase() ?? null; const visibility = read(query.visibility)?.toUpperCase() ?? null; const ordering = read(query.ordering) ?? "-published_at"; let createdFrom = validDate(read(query.created_from)); let createdTo = validDate(read(query.created_to)); if (createdFrom && createdTo && createdFrom > createdTo) [createdFrom, createdTo] = [createdTo, createdFrom]; return { createdFrom, createdTo, ordering: (ORDERING.has(ordering) ? ordering : "-published_at") as ResourceOrdering, page: Number.isSafeInteger(page) && page > 0 && page <= 100_000 ? page : 1, search: search && search.length >= 3 && search.length <= 120 ? search : null, type: type && TYPES.has(type) ? type as ResourceType : null, visibility: visibility && VISIBILITIES.has(visibility) ? visibility as ResourceVisibility : null }; }
export function buildResourcesHref(filters: ResourceFilters) { const query = new URLSearchParams({ page: String(filters.page), ordering: filters.ordering }); set(query, "search", filters.search); set(query, "type", filters.type); set(query, "visibility", filters.visibility); set(query, "created_from", filters.createdFrom); set(query, "created_to", filters.createdTo); return `/resources?${query}`; }
export function resourceInitials(value: string) { return value.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "TM"; }
export function formatResourceDate(value: string | null) { return value ? new Intl.DateTimeFormat("en-RW", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "Available now"; }
export function formatFileSize(value: string | null) { const bytes = Number(value); if (!Number.isFinite(bytes) || bytes <= 0) return "Size unavailable"; if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
export function readResourceError(payload: unknown) { return typeof payload === "object" && payload !== null && "message" in payload && typeof payload.message === "string" ? payload.message : "Resources could not be loaded right now."; }
function read(value: string | string[] | undefined) { const result = Array.isArray(value) ? value[0] : value; return result?.trim() || null; }
function validDate(value: string | null) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null; const date = new Date(`${value}T00:00:00.000Z`); return Number.isNaN(date.getTime()) || !date.toISOString().startsWith(value) ? null : value; }
function set(query: URLSearchParams, key: string, value: string | null) { if (value) query.set(key, value); }
